### ISSUE TITLE
PyBids error

### ISSUE THREAD

**Issue by araikes** [PeerHerholz/BIDSonym#17]
I pulled the latest version of `bidsonym` today. I went to run it and get the following error:

```
scanlab@hope:/data/reading$ docker run -i --rm -v $bidsdir:/bids_dataset peerherholz/bidsonym:latest /bids_dataset participant --deid pydeface --del_nodeface no_del --participant_label RS001
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/bidsonym/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/opt/miniconda-latest/envs/bidsonym/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/miniconda-latest/envs/bidsonym/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pybids 0.10.0 (/opt/miniconda-latest/envs/bidsonym/lib/python3.6/site-packages), Requirement.parse('pybids~=0.9.2'), {'templateflow'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/bidsonym/bin/bidsonym", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/miniconda-latest/envs/bidsonym/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/opt/miniconda-latest/envs/bidsonym/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/opt/miniconda-latest/envs/bidsonym/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/miniconda-latest/envs/bidsonym/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/miniconda-latest/envs/bidsonym/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/miniconda-latest/envs/bidsonym/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pybids 0.10.0 (/opt/miniconda-latest/envs/bidsonym/lib/python3.6/site-packages), Requirement.parse('pybids~=0.9.2'), {'templateflow'})
```

I tried unsetting my PYTHONPATH just to make sure there was no conflict and get the same.

**Comment by PeerHerholz** [comment]
Hi @araikes,

thank you very much for your interested in `BIDSonym` and posting this problem. 
I just pushed some changes to the environment related files and it should work now. The [automated build](https://hub.docker.com/repository/docker/peerherholz/bidsonym) should be done in the next few hours. Could you please try that version as soon as it's up?

**Comment by araikes** [comment]
I pulled it this morning. Same error.

**Comment by PeerHerholz** [comment]
Hi @araikes,

I'm truly sorry for the inconvenience. I changed a few other things related to function imports and tested a local build which it worked as expected. I pushed the respective changes and the [automated build](https://hub.docker.com/repository/docker/peerherholz/bidsonym) should be finished soon-ish. Could you please try that version again?

**Comment by araikes** [comment]
Hi @PeerHerholz,
Sorry for the long lag. Christmas and grant reports got in the way. The new version up worked.

Thanks

**Comment by PeerHerholz** [comment]
No biggie.

Coolio, I will close this issue then.
