### ISSUE TITLE
local variable 'T1_file' referenced before assignment

### ISSUE THREAD

**Issue by hugofluhr** [PeerHerholz/BIDSonym#86]
**Describe the bug**
I get an error when trying to run via docker (latest version). It seems the `T1_file` variable is referenced before assignment

**To Reproduce**
Here is the command I am using:
`sudo docker run -i --rm -v /home/ubuntu/data/bids/ds-learninghabits:/bids_dataset peerherholz/bidsonym /bids_dataset participant --deid pydeface --participant_label 01 --brainextraction bet --bet_frac 0.5 --skip_bids_validation`

**Expected behavior**
I would expect the above command to run without probem

**Screenshots**
Output of the command:
`Some packages in this Docker container are non-free
If you are considering commercial use of this container, please consult the relevant license:
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Licence
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/bidsonym/bin/bidsonym", line 33, in <module>
    sys.exit(load_entry_point('bidsonym', 'console_scripts', 'bidsonym')())
  File "/home/bm/bidsonym/run_deeid.py", line 366, in run_deeid
Input data will not be checked for BIDS compliance.
Found the following session(s) for participant 01:
['1']
    elif len(T1_file) == 1 and args.deface_t2w:
UnboundLocalError: local variable 'T1_file' referenced before assignment`

**OS/environment (please provide precise information on your OS/environment):**
Running on a Ubuntu 22.04 virtual machine.

**Comment by jamesrcoleman97** [comment]
I'm getting the same exact error message after running with the same input command. Any idea on what might be causing this @PeerHerholz
